### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Jun1on** [AffinityGH/AutoZoom#1]
Pls add a better menu for schedules (like minecraft)
Add settings (the ability to change how early you are)
Add auto close tab
Is it possible for autozoom to pretend to be a browser and initiate zoom by itself? if so that would be epic

**Comment by AffinityGH** [comment]
I'm not sure what you mean by pretend to be a browser. Could you elaborate?

**Comment by AffinityGH** [comment]
Added these features.
